// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Clan struct {
	CID       int64
	CName     string
	CPassword string
	CMembers  int64
	EIDLeader int64
	EIDAsst   int64
	EIDFa1    int64
	EIDFa2    int64
	CTitle    string
	CUrl      string
	CPic      string
}

type ClanInvite struct {
	CiID    int64
	CID     interface{}
	EID1    interface{}
	EID2    interface{}
	CiFlags interface{}
	CiTime  int64
}

type ClanMessage struct {
	CmID    int64
	CtID    interface{}
	EID     interface{}
	CmBody  string
	CmTime  int64
	CmFlags interface{}
}

type ClanNews struct {
	CnID    int64
	CnTime  int64
	CID     interface{}
	EID1    interface{}
	CID2    interface{}
	EID2    interface{}
	CnEvent interface{}
}

type ClanRelation struct {
	CrID    int64
	CID1    interface{}
	CID2    interface{}
	CrFlags interface{}
	CrTime  int64
}

type ClanTopic struct {
	CtID      int64
	CID       interface{}
	CtSubject string
	CtFlags   interface{}
}

type Empire struct {
	EID          int64
	UID          int64
	UOldid       int64
	ESignupdate  int64
	EFlags       int64
	EValcode     string
	EReason      string
	EVacation    int64
	EIdle        int64
	EName        int64
	ERace        int64
	EEra         int64
	ERank        int64
	CID          int64
	COldid       int64
	ESharing     int64
	EAttacks     int64
	EOffsucc     int64
	EOfftotal    int64
	EDefsucc     int64
	EDeftotal    int64
	EKills       int64
	EScore       int64
	EKilledby    int64
	EKillclan    int64
	ETurns       int64
	EStoredturns int64
	ETurnsused   int64
	ENetworth    int64
	ECash        int64
	EFood        int64
	EPeasants    int64
	ETrparm      int64
	ETrplnd      int64
	ETrpfly      int64
	ETrpsea      int64
	ETrpwiz      int64
	EHealth      int64
	ERunes       int64
	EIndarm      int64
	EIndlnd      int64
	EIndfly      int64
	EIndsea      int64
	ELand        int64
	EBldpop      int64
	EBldcash     int64
	EBldtrp      int64
	EBldcost     int64
	EBldwiz      int64
	EBldfood     int64
	EBlddef      int64
	EFreeland    int64
	ETax         int64
	EBank        int64
	ELoan        int64
	EMktarm      int64
	EMktlnd      int64
	EMktfly      int64
	EMktsea      int64
	EMktfood     int64
	EMktperarm   int64
	EMktperlnd   int64
	EMktperfly   int64
	EMktpersea   int64
}

type EmpireEffect struct {
	EID     interface{}
	EfName  interface{}
	EfValue int64
}

type EmpireMessage struct {
	MID      int64
	MIDRef   interface{}
	MTime    int64
	EIDSrc   interface{}
	EIDDst   interface{}
	MSubject string
	MBody    string
	MFlags   interface{}
}

type EmpireNews struct {
	NID    int64
	NTime  int64
	EIDSrc interface{}
	CIDSrc interface{}
	EIDDst interface{}
	CIDDst interface{}
	NEvent interface{}
	ND0    int64
	ND1    int64
	ND2    int64
	ND3    int64
	ND4    int64
	ND5    int64
	ND6    int64
	ND7    int64
	ND8    int64
	NFlags interface{}
}

type HistoryClan struct {
	HrID       int64
	HcID       interface{}
	HcMembers  int64
	HcName     string
	HcTitle    string
	HcTotalnet interface{}
}

type HistoryEmpire struct {
	HrID       int64
	HeFlags    interface{}
	UID        interface{}
	HeID       interface{}
	HeName     string
	HeRace     string
	HeEra      string
	HcID       interface{}
	HeOffsucc  interface{}
	HeOfftotal interface{}
	HeDefsucc  interface{}
	HeDeftotal interface{}
	HeKills    interface{}
	HeScore    int64
	HeNetworth interface{}
	HeLand     interface{}
	HeRank     interface{}
}

type HistoryRound struct {
	HrID             int64
	HrName           string
	HrDescription    string
	HrStartdate      int64
	HrStopdate       int64
	HrFlags          interface{}
	HrSmallclansize  interface{}
	HrSmallclans     interface{}
	HrAllclans       interface{}
	HrNonclanempires interface{}
	HrLiveempires    interface{}
	HrDeadempires    interface{}
	HrDelempires     interface{}
	HrAllempires     interface{}
}

type Lock struct {
	LockID interface{}
}

type Log struct {
	LogID     int64
	LogTime   interface{}
	LogType   interface{}
	LogIp     string
	LogPage   string
	LogAction string
	LogLocks  string
	LogText   string
	UID       interface{}
	EID       interface{}
	CID       interface{}
}

type Lottery struct {
	EID     interface{}
	LTicket interface{}
	LCash   interface{}
}

type Market struct {
	KID    int64
	KType  interface{}
	EID    interface{}
	KAmt   interface{}
	KPrice interface{}
	KTime  int64
}

type Permission struct {
	PID         int64
	PType       interface{}
	PCriteria   string
	PComment    string
	PReason     string
	PCreatetime interface{}
	PUpdatetime interface{}
	PLasthit    interface{}
	PHitcount   interface{}
	PExpire     interface{}
}

type Session struct {
	SessID   interface{}
	SessTime interface{}
	SessData []byte
}

type Turnlog struct {
	TurnID       int64
	TurnTime     interface{}
	TurnTicks    interface{}
	TurnInterval interface{}
	TurnType     interface{}
	TurnText     string
}

type User struct {
	UID         int64
	UUsername   string
	UPassword   sql.NullString
	UFlags      sql.NullInt64
	UName       sql.NullString
	UEmail      string
	UComment    sql.NullString
	UTimezone   sql.NullInt64
	UStyle      sql.NullString
	ULang       sql.NullString
	UDateformat sql.NullString
	ULastip     sql.NullString
	UKills      sql.NullInt64
	UDeaths     sql.NullInt64
	UOffsucc    sql.NullInt64
	UOfftotal   sql.NullInt64
	UDefsucc    sql.NullInt64
	UDeftotal   sql.NullInt64
	UNumplays   sql.NullInt64
	USucplays   sql.NullInt64
	UAvgrank    sql.NullFloat64
	UBestrank   sql.NullFloat64
	UCreatedate sql.NullTime
	ULastdate   sql.NullTime
}

type Var struct {
	VName  string
	VValue string
}

type VarAdjust struct {
	VName   interface{}
	VOffset int64
}
